DISTRICT_SEEDS: tuple[tuple[str, str, str], ...] = (
    ("LK-52", "Ampara", "Eastern"),
    ("LK-71", "Anuradhapura", "North Central"),
    ("LK-81", "Badulla", "Uva"),
    ("LK-51", "Batticaloa", "Eastern"),
    ("LK-11", "Colombo", "Western"),
    ("LK-31", "Galle", "Southern"),
    ("LK-12", "Gampaha", "Western"),
    ("LK-33", "Hambantota", "Southern"),
    ("LK-41", "Jaffna", "Northern"),
    ("LK-13", "Kalutara", "Western"),
    ("LK-21", "Kandy", "Central"),
    ("LK-92", "Kegalle", "Sabaragamuwa"),
    ("LK-42", "Kilinochchi", "Northern"),
    ("LK-61", "Kurunegala", "North Western"),
    ("LK-43", "Mannar", "Northern"),
    ("LK-22", "Matale", "Central"),
    ("LK-32", "Matara", "Southern"),
    ("LK-82", "Monaragala", "Uva"),
    ("LK-45", "Mullaitivu", "Northern"),
    ("LK-23", "Nuwara Eliya", "Central"),
    ("LK-72", "Polonnaruwa", "North Central"),
    ("LK-62", "Puttalam", "North Western"),
    ("LK-91", "Ratnapura", "Sabaragamuwa"),
    ("LK-53", "Trincomalee", "Eastern"),
    ("LK-44", "Vavuniya", "Northern"),
)

ROLE_SEEDS: tuple[tuple[str, str], ...] = (
    ("Volunteer", "Updates progress for work assigned to the volunteer."),
    ("ReliefCenterOperator", "Manages inventory and assignments for an owned center."),
    ("Coordinator", "Triages, verifies, assigns, rejects, and cancels requests."),
    ("PlatformOperator", "Operates platform health and delivery without implicit case access."),
)
